config/routes.rb
Rails.application.routes.draw do
  resources :sales_managers
  resources :salespeople
  resources :quotes
  resources :reports
  resources :finances
  resources :customer_types
  resources :customers
  resources :cars do
    member do
      get 'markup'
    end
  end

  get 'homepage/index'

   root 'homepage#index'

end

app/models/finance.rb
class Finance < ActiveRecord::Base

  belongs_to :report
  belongs_to :quote

end

app/controllers/finances_controller.rb
class FinancesController < ApplicationController
  before_action :set_finance, only: [:show, :edit, :update, :destroy]

  # GET /finances
  # GET /finances.json
  def index
    @finances = Finance.all
  end

  # GET /finances/1
  # GET /finances/1.json
  def show
  end

  # GET /finances/new
  def new
    @finance = Finance.new
  end

  # GET /finances/1/edit
  def edit
  end

  # POST /finances
  # POST /finances.json
  def create
    @finance = Finance.new(finance_params)

    respond_to do |format|
      if @finance.save
        format.html { redirect_to @finance, notice: 'Finance was successfully created.' }
        format.json { render :show, status: :created, location: @finance }
      else
        format.html { render :new }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /finances/1
  # PATCH/PUT /finances/1.json
  def update
    respond_to do |format|
      if @finance.update(finance_params)
        format.html { redirect_to @finance, notice: 'Finance was successfully updated.' }
        format.json { render :show, status: :ok, location: @finance }
      else
        format.html { render :edit }
        format.json { render json: @finance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /finances/1
  # DELETE /finances/1.json
  def destroy
    @finance.destroy
    respond_to do |format|
      format.html { redirect_to finances_url, notice: 'Finance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_finance
      @finance = Finance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def finance_params
      params.require(:finance).permit(:quote_id, :report_id, :payment_type, :interest, :period, :length, :finance_id)
    end
end

app/helpers/finances_helper.rb
module FinancesHelper

  def period_num
    [
        ['3'],
        ['4'],
        ['5']
    ]
  end

  def payment_choices
    [
        ['Cash'],
        ['Payment Plan']
    ]
  end


end

app/views/finances/_form.html.erb
<%= form_for(@finance) do |f| %>
  <% if @finance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@finance.errors.count, "error") %> prohibited this finance from being saved:</h2>

      <ul>
      <% @finance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :finance_id%><br>
    <%= f.number_field :finance_id%>
  </div>
  <div class="field">
    <%= f.label :quote_id%><br>
    <%= f.collection_select :quote_id, Quote.all, :id, :full_quote%>
  </div>
  <div class="field">
    <%= f.label :report_id %><br>
    <%= f.number_field :report_id %>
  </div>
  <div class="field">
    <%= f.label :payment_type %><br>
    <%= f.select :payment_type, options_for_select(payment_choices),{}, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </div>
  <div class="field">
    <%= f.label :period %><br>
    <%= f.select :period, options_for_select(period_num),{}, class: 'form-control'  %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/finances/edit.html.erb
<h1>Editing Finance</h1>

<%= render 'form' %>

<%= link_to 'Show', @finance %> |
<%= link_to 'Back', finances_path %>

app/views/finances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Finances</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Quote</th>
      <th>Report</th>
      <th>Payment type</th>
      <th>Interest</th>
      <th>Period</th>
      <th>Length</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @finances.each do |finance| %>
      <tr>
        <td><%= finance.id %></td>
        <td><%= finance.quote_id %></td>
        <td><%= finance.report_id %></td>
        <td><%= finance.payment_type %></td>
        <td><%= finance.interest %></td>
        <td><%= finance.period %></td>
        <td><%= finance.length %></td>
        <td><%= link_to 'Show', finance %></td>
        <td><%= link_to 'Edit', edit_finance_path(finance) %></td>
        <td><%= link_to 'Destroy', finance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Finance', new_finance_path %>

app/views/finances/new.html.erb
<h1>New Finance</h1>

<%= render 'form' %>

<%= link_to 'Back', finances_path %>

app/views/finances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @finance.quote_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @finance.report_id %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @finance.payment_type %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @finance.interest %>
</p>

<p>
  <strong>Period:</strong>
  <%= @finance.period %>
</p>

<p>
  <strong>Length:</strong>
  <%= @finance.length %>
</p>

<%= link_to 'Edit', edit_finance_path(@finance) %> |
<%= link_to 'Back', finances_path %>